In [2]:
import polars as pl

In [49]:
lf = pl.scan_csv("../data/gpt2_rfft.csv")

In [97]:
col = "phase"
lf_amplitude = lf.select(
    pl.col("Tokens"), pl.col(col)
    ).with_columns(
        pl.col(col)
        .str.replace_all(r"\[|\]", "")
        .str.replace(",", "")
        .str.strip_chars()
        .str.replace_all(r"\s+", " ")
        .str.split(" ")
        .cast(pl.List(pl.Float32))
        .list.to_struct(upper_bound=385)
        ).unnest(col)

In [99]:
var = "field_1"
lf_amplitude.select(["Tokens", var]).unique().top_k(10, by=var).collect()

shape: (10, 2)
┌────────┬──────────┐
│ Tokens ┆ field_1  │
│ ---    ┆ ---      │
│ str    ┆ f32      │
╞════════╪══════════╡
│ orts   ┆ 3.141438 │
│ even   ┆ 3.13885  │
│ church ┆ 3.13705  │
│ cember ┆ 3.136302 │
│ mx     ┆ 3.132389 │
│ error  ┆ 3.130494 │
│ import ┆ 3.129979 │
│ ray    ┆ 3.123231 │
│ due    ┆ 3.122914 │
│ or     ┆ 3.12274  │
└────────┴──────────┘

In [92]:
lf.collect()

shape: (17_957, 8)
┌───────┬─────────────┬──────────┬─────────────┬────────────┬────────────┬────────────┬────────────┐
│       ┆ Words       ┆ Tokens   ┆ rfft        ┆ real_rfft  ┆ imag_rfft  ┆ amplitude  ┆ phase      │
│ ---   ┆ ---         ┆ ---      ┆ ---         ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ i64   ┆ str         ┆ str      ┆ str         ┆ str        ┆ str        ┆ str        ┆ str        │
╞═══════╪═════════════╪══════════╪═════════════╪════════════╪════════════╪════════════╪════════════╡
│ 0     ┆ the         ┆ the      ┆ (array([    ┆ [ 1.393529 ┆ [ 0.       ┆ [0.1393529 ┆ [ 1.570796 │
│       ┆             ┆          ┆ 1.39352977e ┆ 77e-01     ┆ -0.2506337 ┆ 8 2.412255 ┆ 4e+00  1.6 │
│       ┆             ┆          ┆ -01,  2.39… ┆ 2.39919925 ┆ 2  1.53…   ┆ 2.47543…   ┆ 748843e+00 │
│       ┆             ┆          ┆             ┆ e+…        ┆            ┆            ┆ …          │
│ 1     ┆ of          ┆ of       ┆ (array([    ┆ [          ┆ [ 0.       ┆ [0.6528697 ┆ [          │
│       ┆             ┆          ┆ 0.6528697 , ┆ 0.6528697  ┆ -1.5385032 ┆ 1.5523338  ┆ 1.5707964  │
│       ┆             ┆          ┆ 0.206756…   ┆ 0.20675689 ┆ 1.69…      ┆ 3.01188…   ┆ 3.0080047  │
│       ┆             ┆          ┆             ┆ -2.48…     ┆            ┆            ┆ -0.97…     │
│ 2     ┆ and         ┆ and      ┆ (array([    ┆ [          ┆ [ 0.000000 ┆ [0.4190853 ┆ [          │
│       ┆             ┆          ┆ 0.41908532, ┆ 0.41908532 ┆ 0e+00  3.2 ┆ 2          ┆ 1.5707964  │
│       ┆             ┆          ┆ -0.233125…  ┆ -0.2331254 ┆ 070851e-01 ┆ 0.39648634 ┆ -0.6285574 │
│       ┆             ┆          ┆             ┆ 5 -1.39…   ┆ …          ┆ 1.50722…   ┆ -1.18…     │
│ 3     ┆ to          ┆ to       ┆ (array([-2. ┆ [-2.215296 ┆ [ 0.000000 ┆ [0.0221529 ┆ [-1.570796 │
│       ┆             ┆          ┆ 2152960e-02 ┆ 0e-02  3.5 ┆ 0e+00  1.8 ┆ 6 4.014954 ┆ 37e+00     │
│       ┆             ┆          ┆ ,  3.549…   ┆ 497758e+00 ┆ 758863e+00 ┆ 3.18128…   ┆ 1.08464706 │
│       ┆             ┆          ┆             ┆ …          ┆ …          ┆            ┆ e+…        │
│ 4     ┆ a           ┆ a        ┆ (array([    ┆ [ 1.887328 ┆ [ 0.       ┆ [0.1887328 ┆ [ 1.570796 │
│       ┆             ┆          ┆ 1.8873286e- ┆ 6e-01  1.6 ┆ -3.528969  ┆ 6          ┆ 4e+00  2.7 │
│       ┆             ┆          ┆ 01,  1.626… ┆ 262540e+00 ┆ 1.76…      ┆ 3.8856564  ┆ 097692e+00 │
│       ┆             ┆          ┆             ┆ …          ┆            ┆ 3.10249…   ┆ …          │
│ …     ┆ …           ┆ …        ┆ …           ┆ …          ┆ …          ┆ …          ┆ …          │
│ 17952 ┆ mediawiki   ┆ wiki     ┆ (array([-1. ┆ [-1.459078 ┆ [ 0.       ┆ [0.1459078 ┆ [-1.570796 │
│       ┆             ┆          ┆ 45907879e-0 ┆ 79e-01 -1. ┆ 1.948009   ┆ 8 2.40204  ┆ 4  -0.6249 │
│       ┆             ┆          ┆ 1, -1.40…   ┆ 40536714e+ ┆ -0.47…     ┆ 3.85446…   ┆ 6924       │
│       ┆             ┆          ┆             ┆ …          ┆            ┆            ┆ -1.69…     │
│ 17953 ┆ configurati ┆ config   ┆ (array([-3. ┆ [-3.226394 ┆ [ 0.000000 ┆ [0.3226394 ┆ [-1.570796 │
│       ┆ ons         ┆          ┆ 22639406e-0 ┆ 06e-01     ┆ 00e+00     ┆ 6.605795   ┆ 4          │
│       ┆             ┆          ┆ 1,  5.36…   ┆ 5.36084557 ┆ 3.85977459 ┆ 1.02696…   ┆ 0.94677746 │
│       ┆             ┆          ┆             ┆ e+…        ┆ e+…        ┆            ┆ 0.07…      │
│ 17954 ┆ configurati ┆ urations ┆ (array([    ┆ [          ┆ [ 0.000000 ┆ [          ┆ [          │
│       ┆ ons         ┆          ┆ 1.4981649 , ┆ 1.4981649  ┆ 00e+00     ┆ 1.4981649  ┆ 1.5707964  │
│       ┆             ┆          ┆ 1.997809…   ┆ 1.9978093  ┆ 3.14424157 ┆ 3.7252512  ┆ 0.56603354 │
│       ┆             ┆          ┆             ┆ -1.70…     ┆ e+…        ┆ 4.14…      ┆ -0.42…     │
│ 17955 ┆ poison      ┆ po       ┆ (array([    ┆ [ 1.149302 ┆ [ 0.000000 ┆ [          ┆ [ 1.570796 │
│       ┆             ┆          ┆ 1.14930

In [100]:
import torch

In [131]:
queen_freq = torch.FloatTensor([0.,1.])
king_freq = torch.FloatTensor([1.,1.])
man_freq = torch.FloatTensor([1.,0.])
wom_freq = torch.FloatTensor([0.,0.])

In [132]:
print(torch.fft.irfft(torch.complex(queen_freq, torch.FloatTensor([0.,0.]))))
print(torch.fft.irfft(torch.complex(king_freq, torch.FloatTensor([0.,0.]))))
print(torch.fft.irfft(torch.complex(man_freq, torch.FloatTensor([0.,0.]))))
print(torch.fft.irfft(torch.complex(wom_freq, torch.FloatTensor([0.,0.]))))

tensor([ 0.5000, -0.5000])
tensor([1., 0.])
tensor([0.5000, 0.5000])
tensor([0., 0.])


tensor([[-0.5674+0.0748j,  0.3939-0.9342j]])


tensor([[-0.2837+0.0374j,  0.1969-0.4671j],
        [-1.1348+0.1497j,  0.7877-1.8684j]])

tensor([[0.+0.j],
        [5.+0.j]])